name: run tests

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - name: checkout
      run: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
       node-version: 20.18
    -name: Install Dependencies
      run: npm ci
    -name: Run tests
      run: npm test